/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "primary": "#c68b58",
        "background-light": "#FDF8F1",
        "bone-white": "#F9F6F2",
        "espresso": "#2C1E1A",
        "caramel": "#C68B59",
        "light": "#FDF8F1",
        // Hotel colors
        "hotel-secondary-fixed": "#ffdf9f",
        "hotel-on-secondary-container": "#785f28",
        "hotel-error-container": "#ffdad6",
        "hotel-on-tertiary-fixed": "#1c1c19",
        "hotel-tertiary-fixed-dim": "#c8c6c2",
        "hotel-on-tertiary": "#ffffff",
        "hotel-secondary-container": "#fedb98",
        "hotel-surface-container-low": "#ecf4ff",
        "hotel-on-error": "#ffffff",
        "hotel-secondary-fixed-dim": "#e3c281",
        "hotel-tertiary-container": "#2c2c29",
        "hotel-outline-variant": "#c4c6cf",
        "hotel-inverse-primary": "#aec8f3",
        "hotel-on-surface-variant": "#43474e",
        "hotel-surface-container": "#e5effb",
        "hotel-on-tertiary-container": "#95938f",
        "hotel-on-primary": "#ffffff",
        "hotel-on-background": "#131d25",
        "hotel-on-primary-container": "#7b94bd",
        "hotel-secondary": "#735b24",
        "hotel-inverse-on-surface": "#e8f2fe",
        "hotel-primary-fixed": "#d5e3ff",
        "hotel-tertiary-fixed": "#e5e2dd",
        "hotel-primary-fixed-dim": "#aec8f3",
        "hotel-on-primary-fixed": "#001c3b",
        "hotel-on-error-container": "#93000a",
        "hotel-outline": "#74777f",
        "hotel-surface-bright": "#f7f9ff",
        "hotel-on-primary-fixed-variant": "#2e486c",
        "hotel-background": "#f7f9ff",
        "hotel-surface": "#f7f9ff",
        "hotel-inverse-surface": "#28313a",
        "hotel-error": "#ba1a1a",
        "hotel-on-secondary-fixed": "#261a00",
        "hotel-on-secondary-fixed-variant": "#5a430e",
        "hotel-on-secondary": "#ffffff",
        "hotel-surface-tint": "#465f85",
        "hotel-surface-container-high": "#dfe9f5",
        "hotel-primary-container": "#0f2c4f",
        "hotel-surface-dim": "#d1dbe7",
        "hotel-on-tertiary-fixed-variant": "#474743",
        "hotel-primary": "#001733",
        "hotel-surface-container-highest": "#d9e4ef",
        "hotel-surface-variant": "#d9e4ef",
        "hotel-tertiary": "#171815",
        "hotel-surface-container-lowest": "#ffffff",
        "hotel-on-surface": "#131d25"
      },
      fontFamily: {
        "display": ["Work Sans", "sans-serif"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "display-lg": ["Playfair Display"],
        "headline-lg": ["Playfair Display"],
        "headline-md": ["Playfair Display"],
        "caption": ["Inter"],
        "display-lg-mobile": ["Playfair Display"],
        "body-lg": ["Inter"]
      },
      spacing: {
        "gutter": "24px",
        "margin-desktop": "64px",
        "lg": "48px",
        "md": "24px",
        "sm": "12px",
        "margin-mobile": "20px",
        "base": "8px",
        "xs": "4px",
        "xl": "80px",
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "display-lg": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["48px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "headline-md": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "caption": ["12px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "display-lg-mobile": ["40px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      zIndex: {
        "1000": "1000",
      }
    },
  },
  plugins: [],
}
